apiVersion: v1
kind: Service
metadata:
  name: clickhouse-mcp-server
  labels:
    app.kubernetes.io/name: clickhouse-mcp-server
    app.kubernetes.io/part-of: krateo-observability-stack
spec:
  type: {{ .Values.service.type }}
  selector:
    app: clickhouse-mcp-server
  ports:
    - name: mcp
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
